export type TradingAssetCategory =
  | "Валютные пары"
  | "Криптовалюты"
  | "Сырьевые товары"
  | "Акции"
  | "Индексы";

export type TradingAssetGroup = {
  title: TradingAssetCategory;
  items: string[];
};

export const tradingAssetGroups: TradingAssetGroup[] = [
  {
    title: "Валютные пары",
    items: [
      "AED/CNY OTC",
      "AUD/CAD OTC",
      "AUD/NZD OTC",
      "AUD/USD OTC",
      "BHD/CNY OTC",
      "CAD/CHF OTC",
      "CAD/JPY OTC",
      "CHF/JPY OTC",
      "CHF/NOK OTC",
      "EUR/CHF OTC",
      "EUR/JPY OTC",
      "GBP/JPY OTC",
      "GBP/USD OTC",
      "JOD/CNY OTC",
      "KES/USD OTC",
      "LBP/USD OTC",
      "MAD/USD OTC",
      "NGN/USD OTC",
      "NZD/USD OTC",
      "TND/USD OTC",
      "USD/ARS OTC",
      "USD/BDT OTC",
      "USD/BRL OTC",
      "USD/CNH OTC",
      "USD/COP OTC",
      "USD/DZD OTC",
      "USD/EGP OTC",
      "USD/IDR OTC",
      "USD/INR OTC",
      "USD/JPY OTC",
      "USD/PHP OTC",
      "USD/SGD OTC",
      "USD/THB OTC",
      "USD/VND OTC",
      "YER/USD OTC",
      "GBP/AUD OTC",
      "AUD/JPY OTC",
      "OMR/CNY OTC",
      "EUR/GBP OTC",
      "USD/MXN OTC",
      "EUR/NZD OTC",
      "USD/MYR OTC",
      "USD/PKR OTC",
      "EUR/TRY OTC",
      "USD/CHF OTC",
      "EUR/USD OTC",
      "EUR/RUB OTC",
      "ZAR/USD OTC",
      "USD/RUB OTC",
      "UAH/USD OTC",
      "QAR/CNY OTC",
      "EUR/HUF OTC",
      "USD/CLP OTC",
      "AUD/CHF OTC",
      "NZD/JPY OTC",
      "USD/CAD OTC",
      "SAR/CNY OTC",
    ],
  },
  {
    title: "Криптовалюты",
    items: [
      "Cardano OTC",
      "Bitcoin ETF OTC",
      "Bitcoin OTC",
      "Ethereum OTC",
      "Litecoin OTC",
      "Solana OTC",
      "Toncoin OTC",
      "TRON OTC",
      "Avalanche OTC",
      "Chainlink OTC",
      "Dogecoin OTC",
      "Polkadot OTC",
      "Polygon OTC",
      "BNB OTC",
      "Bitcoin",
    ],
  },
  {
    title: "Сырьевые товары",
    items: [
      "Brent Oil OTC",
      "WTI Crude Oil OTC",
      "Silver OTC",
      "Gold OTC",
      "Natural Gas OTC",
      "Palladium spot OTC",
      "Platinum spot OTC",
    ],
  },
  {
    title: "Акции",
    items: [
      "Apple OTC",
      "McDonald's OTC",
      "ExxonMobil OTC",
      "Alibaba OTC",
      "FedEx OTC",
      "Netflix OTC",
      "VISA OTC",
      "Coinbase Global OTC",
      "Pfizer Inc OTC",
      "Marathon Digital Holdings OTC",
      "Cisco OTC",
      "Tesla OTC",
      "Boeing Company OTC",
      "Intel OTC",
      "Microsoft OTC",
      "Johnson & Johnson OTC",
      "Amazon OTC",
      "Palantir Technologies OTC",
      "Advanced Micro Devices OTC",
      "American Express OTC",
      "Citigroup Inc OTC",
      "GameStop Corp OTC",
      "FACEBOOK INC OTC",
      "VIX OTC",
    ],
  },
  {
    title: "Индексы",
    items: [
      "AUS 200 OTC",
      "100GBP OTC",
      "D30EUR OTC",
      "DJI30 OTC",
      "E35EUR OTC",
      "E50EUR OTC",
      "F40EUR OTC",
      "JPN225 OTC",
      "US100 OTC",
      "SP500 OTC",
    ],
  },
];

export const allTradingAssets = tradingAssetGroups.flatMap((g) => g.items);